package com.example.ssafy301.player.domain;

public enum Position {
    // formalName으로 작성
    PITCHER, CATCHER, FIRST_BASE, SECOND_BASE, THIRD_BASE, SHORTSTOP,LEFT_FIELDER,
    CENTER_FIELDER, RIGHT_FIELDER, DESIGNATED_HITTER, PINCH_HITTER, PINCH_RUNNER, EXTRA_HITTER,
    BASE_RUNNER, OUTFIELD, INFIELD, STARTING_PITCHER, RELIEF_PITCHER, CLOSER, UTILITY, UTILITY_INFIELDER,
    UTILITY_OUTFIELDER, RIGHT_HANDED_PITCHER, LEFT_HANDED_PITCHER, RIGHT_HANDED_STARTER, LEFT_HANDED_STARTER,
    LEFT_HANDED_RELIEVER, RIGHT_HANDED_RELIEVER, PITCHER_INFIELDER, PITCHER_OUTFIELDER, PITCHER_UTILITY,
    TWO_WAY_PLAYER, BATTER, RUNNER_ON_FIRST, RUNNER_ON_SECOND, RUNNER_ON_THIRD, OUTFIELDER, INFIELDER

}
